### ISSUE TITLE
Short solution needed: "How to fold" (vim)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#814]
Please help us write most modern and shortest code solution for this issue:
**How to fold** (technology: [vim](https://onelinerhub.com/vim))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn
 Sir, May I know why am I getting this error ?
$ git push origin Rithya
remote: Permission to Onelinerhub/onelinerhub.git denied to RithyaReddy.
fatal: unable to access 'https://github.com/Onelinerhub/onelinerhub.git/': The requested URL returned error: 403

![File_denied](https://user-images.githubusercontent.com/94788506/149629971-51c4096e-ec31-4ed9-a4d4-a039fef18cc2.png)

**Comment by RithyaReddy** [comment]
zc

**Comment by nonunicorn** [comment]
That's because you should [create pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) instead of pushing changes directly.

**Comment by RithyaReddy** [comment]
But during that I have encountered with another error where I have searched in google and asked some of my seniors but I didn't do it intentionally.

**ERROR**
$ git push origin RithyaReddy
To https://github.com/RithyaReddy/onelinerhub.git
 ! [rejected]        RithyaReddy -> RithyaReddy (non-fast-forward)
error: failed to push some refs to 'https://github.com/RithyaReddy/onelinerhub.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**This is the error previously encountered my me sir.
I am sorry sir. Sir, can you please remove the restriction and look into the the above error also.**

**Comment by nonunicorn** [comment]
Oh, it seems like you need to `git pull` from your fork first, then do the push and only then - create pull request to our repository. Let me know if that helps.

**Comment by RithyaReddy** [comment]
@nonunicorn 
Thankyou sir 
I am able to do now

**Comment by nonunicorn** [comment]
[How to fold on indent](https://onelinerhub.com/vim/how-to-fold-on-indent)
