### ISSUE TITLE
Short solution needed: "How to change password in CLI" (ubuntu)

### ISSUE THREAD

**Issue by nonunicorn** [Onelinerhub/onelinerhub#920]
Please help us write most modern and shortest code solution for this issue:
**How to change password in CLI** (technology: [ubuntu](https://onelinerhub.com/ubuntu))

### Fast way
Just write the code solution in the comments.

### Prefered way
1. Create pull request with a new code file inside [inbox folder](https://github.com/Onelinerhub/onelinerhub/tree/main/inbox).
2. Don't forget to use comments to make solution explained.
3. Link to this issue in comments of pull request.

**Comment by RithyaReddy** [comment]
@nonunicorn
sir, I am facing the same issue again
$ git push origin RithyaReddy
To https://github.com/RithyaReddy/onelinerhub.git
 ! [rejected]        RithyaReddy -> RithyaReddy (non-fast-forward)
error: failed to push some refs to 'https://github.com/RithyaReddy/onelinerhub.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by RithyaReddy** [comment]
![recentError](https://user-images.githubusercontent.com/94788506/150126611-5e80b6e8-da91-4260-9761-50da0b20ed60.png)

**Comment by nonunicorn** [comment]
Seems like you need to `git pull` again :)

**Comment by RithyaReddy** [comment]
@nonunicorn 
okay sir, thank you

**Comment by nonunicorn** [comment]
[How to generate password in CLI](https://onelinerhub.com/ubuntu/how-to-generate-password-in-cli)
